name: Terraform Checks
on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  fmt-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
      - name: Terraform fmt
        run: terraform fmt -recursive
      - name: Terraform validate
        run: terraform init -backend=false && terraform validate
